### PR TITLE
Tony/navigation

### PR DESCRIPTION
**Pull request by tonyboylehub**

### CODE REVIEW

**Comment by blockiosaurus** [comment]
Seeing the same issue mentioned this morning (No products in dropdown) on desktop as well. Also can you update the links in the Developer Tools page to point to these new tools instead of Github?

**Comment by MarkSackerberg** [comment]
The Product part 
image
seems to be scrollable on desktop (Firefox, Chrome) but not on mobile (Safari)

**Comment by tonyboylehub** [comment]
@MarkSackerberg can you check mobile nav again?

**Comment by blockiosaurus** [comment]
It looks like "Browse our Products" can't find a page.

**Comment by MarkSackerberg** [comment]
Scrolling is working now on safari. Thank you @tonyboylehub

**Comment by tonyboylehub** [comment]
> It looks like "Browse our Products" can't find a page.

good shout. Me and Stephan renamed that change. Will update.

**Review by MarkSackerberg — DISMISSED** [review]

**Review by MarkSackerberg — APPROVED** [review]

**Pull request merged**
